#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ ! -f "$DIR/vars.sh" ]
then
	exit 1
fi

. $DIR/vars.sh
while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-name)
		    NAME=$2
		    PROJECT_DIR=`echo -n $PROJECT_DIR | sed s/@NAME/"$NAME"/`
		    shift
		    shift
		    ;;
		-reference)
		    REFERENCE=$2
		    PROJECT_DIR=`echo -n $PROJECT_DIR | sed s/@REFERENCE/"$REFERENCE"/`
		    shift
		    shift
		    ;;
		-year)
		    YEAR=$2
		    PROJECT_DIR=`echo -n $PROJECT_DIR | sed s/@YEAR/"$YEAR"/`
		    shift
		    shift
		    ;;
		*)
		    shift
		    shift
		    ;;
	esac
done

if [ ! -z "$REFERENCE" ] && [ ! -z "$NAME" ]
then
	if [ ! -d "$PROJECT_DIR" ]
	then
		mkdir -p "$PROJECT_DIR"
	fi
fi
exit 0
